kind: pipeline
type: docker
name: deploy

steps:
- name: deploy
  image: dokku/ci-docker-image
  pull: always
  environment:
    DOKKU_HOST: apps1.fnukinternal.net
    DOKKU_APP_NAME: dokku-ci-deploy
    DOKKU_USERNAME: dokku
    SSH_PRIVATE_KEY:
      from_secret: dokku_ssh_key
    JUMP_HOST: 192.168.0.24
    JUMP_USER: jumpuser
    JUMP_PRIVATE_KEY:
      from_secret: dokku_ssh_key
  commands:
  - mkdir -p ~/.ssh
  - echo "$JUMP_PRIVATE_KEY" > ~/.ssh/id_rsa_jump
  - chmod 600 ~/.ssh/id_rsa_jump
  - echo "Host $DOKKU_HOST" > ~/.ssh/config
  - echo "  ProxyCommand ssh -W %h:%p $JUMP_USER@$JUMP_HOST -i ~/.ssh/id_rsa_jump" >> ~/.ssh/config
  - dokku apps:create $DOKKU_APP_NAME
  - dokku git:sync --force $DOKKU_APP_NAME

trigger:
  branch:
    - main
