kind: pipeline
type: docker
name: deploy-to-dokku

steps:
  - name: deploy
    image: dokku/ci-docker-image
    settings:
      dokku_host: apps1.fnukinternal.net # replace with your Dokku host
      dokku_app: dokku-ci-deploy # replace with your Dokku app name
      dokku_key:
        from_secret: dokku_ssh_key
      dokku_git_remote: dokku@apps1.fnukinternal.net:dokku-ci-deploy
      dokku_jump_host: 192.168.0.24 # replace with your jump host
      dokku_jump_user: jumpuser # replace with the user to use on the jump host
      dokku_jump_key:
        from_secret: dokku_ssh_key
      dokku_force_push: "true"
      dokku_confirm: "true"
      dokku_sync_networks: "true"
      dokku_build_dir: "."
      dokku_deploy_branch: main # replace with the branch you want to deploy

trigger:
  branch:
    - main
